# Generated by Django 2.2 on 2019-05-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haytunes', '0003_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.FileField(default=1, upload_to='product'),
            preserve_default=False,
        ),
    ]
