# Generated by Django 2.2 on 2019-05-09 07:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('haytunes', '0006_auto_20190509_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular product across', primary_key=True, serialize=False),
        ),
    ]
