# Generated by Django 2.2 on 2019-05-09 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('haytunes', '0007_auto_20190509_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ManyToManyField(help_text='Select an owner for this product.', to=settings.AUTH_USER_MODEL),
        ),
    ]
