# Generated by Django 2.2 on 2019-05-09 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haytunes', '0009_auto_20190509_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ManyToManyField(blank=True, help_text='Select an owner for this product.', to=settings.AUTH_USER_MODEL),
        ),
    ]
